version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/openjdk:21.0

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Set up Docker daemon
          command: |
            apk add --no-cache docker
            dockerd-entrypoint.sh &
            sleep 10
      - run:
          name: Build Maven project
          command: mvn clean package
      - run:
          name: Setup Minikube Docker env
          command: |
            eval $(minikube docker-env)
      - run:
          name: Build Docker Image
          command: docker build -t helloworld:latest .
      - run:
          name: Apply Kubernetes Manifests
          command: |
            kubectl apply -f k8s/

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
